org: subhamayaws
app: aws-node-project
service: azalea-nodejs-lambda-sample-20

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: serverless-admin
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    REGION_NAME: ${self:provider.region}
    REPLY_TABLE: Reply

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'ses:*'

functions:
  sendEmailUsingSES:
    name: azalea-send-email-using-ses-${self:provider.stage}-${self:provider.region}
    description: To send email via SES using AWS-SDK
    handler: handler.sendEmailUsingSES
    events:
      - http:
          path: /send-email
          method: post
          cors: true

