org: subhamayaws
app: aws-node-project
service: azalea-nodejs-lambda-sample-14

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: serverless-admin
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    REGION_NAME: ${self:provider.region}
    PRODUCT_CATALOG_TABLE: ProductCatalog

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:*'

functions:
  getDynamoDBItem:
    name: azalea-get-dynamodb-item-${self:provider.stage}-${self:provider.region}
    description: To get an item from a DynamoDB table using AWS-SDK
    handler: handler.getDynamoDBItem

resources: # CloudFormation template syntax from here on.
  Resources:
    ProductCatalogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductCatalog
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: N
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  Outputs:
    DynamoDBTableArn: 
      Description: The Arn of the DynamoDB Table
      Value: !GetAtt ProductCatalogTable.Arn


