org: subhamayaws
app: aws-node-project
service: azalea-nodejs-lambda-sample-8

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: serverless-admin
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    REGION_NAME: ${self:provider.region}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'

functions:
  appendingToAnObjectInS3:
    name: azalea-appending-to-s3-object-${self:provider.stage}-${self:provider.region}
    description: To append to an object in a S3 bucket using AWS-SDK
    handler: handler.appendingToAnObjectInS3


